Add support for different flow styles in Sequences
charleskorn/kaml pull request #40
Opened 2020-08-30 21:54 UTC by knightzmc

This adds support for the Flow Style of rendering Sequences, by adding a parameter to `YamlConfiguration`

The default block style is still used to avoid breaking anything.

This is referenced in #33

2020-08-31 06:25 UTC, charleskorn commented
Hey @knightzmc, thanks for the PR. It looks like the formatting check is failing - could you please run `./gradlew spotlessApply` to fix any issues and push that change?

2020-08-31 12:12 UTC, knightzmc commented
Oh, that's weird. When I ran the tests it told me that spotless had failed so I formatted it. Must've accidentally changed something

2020-08-31 13:30 UTC, knightzmc commented
@charleskorn I ran spotless again, it seemed to have fixed all of the formatting issues.

2020-09-01 10:33 UTC, charleskorn requested changes
Thanks again for this PR. It looks good to me - there are only two minor things and then I think this should be good to merge.

2020-09-01 10:33 UTC, charleskorn commented on src/test/kotlin/com/charleskorn/kaml/YamlWritingTest.kt
> +                val serializer =
Could you please revert all of the unrelated formatting changes here and below? (this helps keep the diff clean and focused on the changes you've made)

2020-09-01 10:33 UTC, charleskorn commented on src/main/kotlin/com/charleskorn/kaml/YamlConfiguration.kt
> +    internal val sequenceStyle: SequenceStyle = SequenceStyle.Block
Could you please add a short description of this parameter in the documentation comment above?

2020-09-01 10:33 UTC, charleskorn commented on src/main/kotlin/com/charleskorn/kaml/YamlConfiguration.kt
> +    internal val sequenceStyle: SequenceStyle = SequenceStyle.Block
Something like this would be enough:

```
[sequenceStyle]: how to format sequences (lists or arrays) when encoding them as YAML
```

2020-09-01 20:21 UTC, knightzmc commented
Hi @charleskorn I've gone through the diff and reverted all of the accidental test changes, along with adding a simple doc

2020-09-03 06:45 UTC, charleskorn commented
Looks great, thanks again for the PR @knightzmc!

2020-09-03 06:45 UTC, merged